# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: domain_prefix 1.0.20241203 ruby lib

Gem::Specification.new do |s|
  s.name = "domain_prefix".freeze
  s.version = "1.0.20241203".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Scott Tadman".freeze]
  s.date = "2024-12-03"
  s.description = "A library to extract information about top-level domain and registered name from generic and international domain names".freeze
  s.email = "tadman@postageapp.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".travis.yml",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "data/effective_tld_names.dat",
    "domain_prefix.gemspec",
    "lib/domain_prefix.rb",
    "lib/domain_prefix/tree.rb",
    "test/helper.rb",
    "test/sample/README",
    "test/sample/test.txt",
    "test/test_domain_prefix.rb"
  ]
  s.homepage = "http://github.com/postageapp/domain_prefix".freeze
  s.rubygems_version = "3.5.22".freeze
  s.summary = "Domain Prefix Extraction Library".freeze

  s.specification_version = 4

  s.add_runtime_dependency(%q<simpleidn>.freeze, [">= 0.0.5".freeze])
  s.add_runtime_dependency(%q<json>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<test-unit>.freeze, [">= 0".freeze])
  s.add_development_dependency(%q<juwelier>.freeze, [">= 0".freeze])
end

